### ISSUE TITLE
Huggingface's Tranformers implementation?

### ISSUE THREAD

**Issue by thedarkzeno** [timojl/clipseg#16]
Is there an implementation that uses the clip model from the transformers lib? If not how hard would it be to implement?

**Comment by timojl** [comment]
I'm not aware of any such implementation. What would be the advantage? I prefer using the CLIP code to Huggingface Transformers since the latter comes with several dependencies. However, implementing it should be straightforward by replacing the CLIP initialization here: https://github.com/timojl/clipseg/blob/master/models/clipseg.py#L86

**Comment by NielsRogge** [comment]
Hi,

See #18

**Comment by thedarkzeno** [comment]
> Hi,
> 
> See #18

@NielsRogge 
Great, I had implemented a version that supported de HFs models, but it's good to see an official implementation.
Will there be a training script with the transformers framework?
