### ISSUE TITLE
only image with mask

### ISSUE THREAD

**Issue by senlin-ali** [timojl/clipseg#6]
hi、 i am interested in your work and i want to know if input is only image with mask, can it output  mask object with the orginal image; also i want to know where is the lvis_oneshot dataset.   thanks!

**Comment by timojl** [comment]
The output is always a binary segmentation of the query image. The support image with a mask (or the text prompt) specifies what to segment in the query image.
Since the LVIS dataset is not central for the paper, I decided to exclude it from the repository for the sake of simplicity. In earlier commits it was included, though. You can find it here: https://github.com/timojl/clipseg/blob/992398d253c200f47e407b8d0e6eb9cd454314fc/datasets/lvis_oneshot3.py
